# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: lazy-pulumi

snapshot:
  version_template: '{{ .Tag }}-SNAPSHOT'

builds:
  # Linux builds using cargo-zigbuild for cross-compilation
  - id: lazy-pulumi-linux
    builder: rust
    binary: lazy-pulumi
    command: zigbuild
    flags:
      - --release
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu

  # macOS builds using cargo (native)
  - id: lazy-pulumi-darwin
    builder: rust
    binary: lazy-pulumi
    command: build
    flags:
      - --release
    targets:
      - aarch64-apple-darwin
      - x86_64-apple-darwin

archives:
  - format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

homebrew_casks:
  - name: lazy-pulumi
    repository:
      owner: dirien
      name: homebrew-dirien
      branch: main

    commit_author:
      name: dirien
      email: engin.diri@mail.schwarz

    directory: Casks
    homepage: "https://github.com/dirien/lazy-pulumi"
    description: "A stylish TUI for Pulumi Cloud, ESC, and NEO"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
