//! Auto-generated Pulumi API client (via progenitor from OpenAPI spec).
//!
//! DO NOT EDIT — regenerated by build.rs from openapi/pulumi-spec.json.

mod inner {
    #![allow(clippy::all, unused_imports, dead_code)]
    include!(concat!(env!("OUT_DIR"), "/pulumi_api.rs"));
}

pub use inner::*;
